language: go
go:
  - tip
before_install:
  - wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libimage-exiftool-perl/libimage-exiftool-perl_10.10-1_all.deb
  - sudo dpkg -i libimage-exiftool-perl_10.10-1_all.deb
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci ./...

